version: '3'

services:
  listener:
    image: ljhskyso/alphasmithy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ENV: production
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        delay: 10s
      restart_policy:
        condition: on-failure